apiVersion: v1
kind: Service
metadata:
  name: voting-backend
  namespace: voting-app
spec:
  selector:
    app: voting-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP 