apiVersion: v1
kind: Service
metadata:
  name: voting-frontend
  namespace: voting-app
spec:
  selector:
    app: voting-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP 