groups:
- name: security
  rules:
  - alert: HighFailedLoginAttempts
    expr: rate(http_requests_total{status=~"401|403"}[5m]) > 5
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: High number of failed login attempts
      description: "{{ $value }} failed login attempts per second"

  - alert: UnusualTrafficPattern
    expr: abs(rate(http_requests_total[5m]) - avg_over_time(http_requests_total[1h])) > 3 * stddev_over_time(http_requests_total[1h])
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Unusual traffic pattern detected
      description: "Current request rate: {{ $value }}"

  - alert: HighErrorRate
    expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.01
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: High error rate detected
      description: "Error rate: {{ $value }}"

  - alert: DatabaseConnectionIssues
    expr: pg_up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Database connection issues
      description: "Database is not responding"

  - alert: HighCPUUsage
    expr: rate(process_cpu_seconds_total[5m]) > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High CPU usage
      description: "CPU usage: {{ $value }}"

  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High memory usage
      description: "Memory usage: {{ $value }}" 